### ISSUE TITLE
Link vechi care necesita actualizare

### ISSUE THREAD

**Issue by SebiAlecu** [SoftulmeuRo/gltfacturare#2]
Pasul 1: Accesez link-ul "expresor travelform"
![link1](https://cloud.githubusercontent.com/assets/12894907/9547645/5cbdc254-4da4-11e5-8b7d-78b062efbab4.PNG)  
Pasul 2: Link-ul "https://expresor.softulmeu.ro/travelform/Ecrane/document.aspx?screen=Rezervari" este vechi, iar serverul nu este gasit
![link2](https://cloud.githubusercontent.com/assets/12894907/9547689/b2c235ae-4da4-11e5-81a8-632e6977794f.PNG)

Trebuie actualizat cu noul link : "https://dev2.softulmeu.ro/travelform/Ecrane/document.aspx?screen=Rezervari"

**Comment by SebiAlecu** [comment]
Link-ul nu este in aplicatie si nu poate fi corectat de catre un dezvoltator

**Comment by t1b1c** [comment]
l-am corectat, verifica pls si inchide

**Comment by SebiAlecu** [comment]
am verificat, e ok.
